# Configurations
title:            The Constant Companions Handbook
longtitle:        lipu linluwi pona - The Constant Companions Handbook
author:           Ellis of the Pleiadesfolk, Cheerleader System, Catherine Cowie et al. 
email:            pleaidesfolk@proton.me
description: >
  lipu linluwi pona is a handbook for plurality, a state in which multiple self-aware entities reside in one physical brain.
 
version:          0.1
gitbook_version:  3.2.3

url:              'https://pleaidesfolk.github.io'
baseurl:          ''
rss:              RSS

toc:
  enabled: true
  h_min:   1
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext       

# OGP image
defaults:
  - scope:
      path: ""
    values:
      image: /assets/media/default-ogp.png


exclude:
  - _drafts

collections:
  guide:
    output: true
    permalink: /:collection/:path/
  essays:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - guide
  - essays
  - others

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-readme-index
  - jemoji
